[package]
name = "synthesthesia"
version = "0.1.0"
authors = ["Marcus Friis Klausen"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/MarcusFriisKlausen/synthesthesia/"

[dependencies]
midir = "0.9.1"
rodio = "0.17.3"
